/* SPDX-License-Identifier: GPL-2.0 */
/*
 * gaia_qemu_bridge.h
 *
 * Minimal C ABI for the GAIA QMP bridge.
 *
 * Trust model:
 *   - This bridge is NOT a trust boundary.
 *   - All commands sent through it are generated by the Rust VMM.
 *   - QEMU is treated as an untrusted device-model process.
 *   - The Rust VMM retains exclusive ownership of /dev/kvm fds.
 *
 * Spec ref: VIRT-MEM-IPC-SPEC §3.5, §8
 */

#ifndef GAIA_QEMU_BRIDGE_H
#define GAIA_QEMU_BRIDGE_H

#ifdef __cplusplus
extern "C" {
#endif

/**
 * gaia_qmp_open - Connect to a QEMU QMP Unix domain socket.
 *
 * @unix_socket_path: Path to the QMP socket (e.g. "/run/gaia/qemu-sophia.sock")
 *
 * Returns a connected file descriptor on success, -1 on error.
 * The caller is responsible for calling gaia_qmp_close() when done.
 */
int gaia_qmp_open(const char *unix_socket_path);

/**
 * gaia_qmp_send_raw - Write a raw JSON line to an open QMP socket.
 *
 * @fd:        File descriptor returned by gaia_qmp_open().
 * @json_line: Null-terminated JSON string. Must be a complete QMP command.
 *
 * Returns 0 on success, -1 if the write was short or failed.
 *
 * Note: QMP requires a handshake (capabilities negotiation) before commands
 * are accepted. The caller must send the negotiate message first.
 */
int gaia_qmp_send_raw(int fd, const char *json_line);

/**
 * gaia_qmp_close - Close a QMP socket connection.
 *
 * @fd: File descriptor to close.
 *
 * Returns 0 on success, -1 on error (see close(2)).
 */
int gaia_qmp_close(int fd);

#ifdef __cplusplus
}
#endif

#endif /* GAIA_QEMU_BRIDGE_H */
