---
- name: start and enable docker
  ansible.builtin.service:
    name:    docker
    state:   started
    enabled: true

- name: start and enable containerd
  ansible.builtin.service:
    name:    containerd
    state:   started
    enabled: true
